from typing import Optional, Protocol

from realsense_cli.types import DeviceInfo, Sensor, Option, Profile, FrameSet


class DriverProtocol(Protocol):
    @property
    def sensors(self) -> list[Sensor]: ...

    @property
    def active_device(self) -> str: ...

    @active_device.setter
    def active_device(self, serial: Optional[str]) -> None: ...

    def query_devices(self) -> list[DeviceInfo]: ...

    def list_controls(self, sensor: Sensor) -> list[Option]: ...

    def get_control_values(self, sensor: Sensor, controls: list[str]) -> dict[str, float]: ...

    def set_control_values(self, sensor: Sensor, control_values: dict[str, float]) -> None: ...

    def list_streams(self, sensor: Sensor) -> list[Profile]: ...

    def play(self, profiles: Optional[list[Profile]] = None, pipeline: bool = True) -> None: ...

    def stop(self) -> None: ...

    def wait_for_frameset(self, timeout: float = 3.0) -> Optional[FrameSet]: ...

    def reset(self) -> None: ...
